services:
  frontend:
    build:
      context: ./FrontEnd
    ports:
      - "3000:3000"
    depends_on:
      - middle_api
    networks:
      - myinternalnetwork

  middle_api:
    build:
      context: ./my_middle_API
    env_file:
      - storage/secrets/secrets_database.env
    ports:
      - "8000:8000"
    networks:
      - myinternalnetwork
    depends_on:
      - db

  db:
    build: ./storage/postgres
    env_file:
      - storage/secrets/secrets_database.env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - myinternalnetwork

  pgadmin:
    build:
      context: .
      dockerfile: pgadmin/Dockerfile
    env_file:
      - storage/secrets/secrets_database.env
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - myinternalnetwork

  mailpit:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    depends_on:
      - frontend
    networks:
      - myinternalnetwork

networks:
  myinternalnetwork:


volumes:
  db_data:
