
services:
  frontend:
    build:
      context: ./FrontEnd
    ports:
      - "3000:3000"
    depends_on:
      - middle_api
    networks:
      - myinternalnetwork
    
  middle_api:
    build:
      context: ./my_middle_API
    ports:
      - "8000:8000"
    networks:
      - myinternalnetwork



networks:
  myinternalnetwork:
