name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual trigger'
        required: false
        default: 'Manual build and deploy'

env:
  GITHUB_REPOSITORY: ${{ github.repository }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Update submodules
      run: |
        git submodule update --remote --recursive --merge
        git submodule foreach 'git checkout main && git pull origin main'

    - name: Replace values in files
      run: |
        sed -i 's|/fastapi|/dev/fastapi|g; s|:8000|:8001|g; s|:3000|:3001|g' FrontEnd/src/urls.json my_middle_API/config_factory.py
        sed -i 's|8000|8001|g' my_middle_API/Dockerfile
        sed -i 's|8000|8001|g; s|host="127.0.0.1"|host="0.0.0.0"|g' my_middle_API/run_apps.py
        sed -i 's|3000|3001|g' FrontEnd/Dockerfile

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and push Frontend image
      uses: docker/build-push-action@v2
      with:
        context: ./FrontEnd
        push: true
        tags: ghcr.io/${{ github.repository }}/frontend:latest

    - name: Build and push Middle API image
      uses: docker/build-push-action@v2
      with:
        context: ./my_middle_API
        push: true
        tags: ghcr.io/${{ github.repository }}/middle-api:latest

    - name: Build and push DB image
      uses: docker/build-push-action@v2
      with:
        context: ./storage/postgres
        push: true
        tags: ghcr.io/${{ github.repository }}/db:latest

    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /root/s_locator
          git pull
          docker-compose -f docker-compose.dev.yml down
          docker-compose -f docker-compose.dev.yml pull
          docker-compose -f docker-compose.dev.yml up -d